"""pets table has PK as 'id' 

Revision ID: e4d3d7c4cd31
Revises: 15a8cf29de00
Create Date: 2025-09-17 18:24:29.311669

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'e4d3d7c4cd31'
down_revision: Union[str, Sequence[str], None] = '15a8cf29de00'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # First, drop the foreign key constraint
    op.drop_constraint(op.f('bookings_pet_id_fkey'), 'bookings', type_='foreignkey')
    
    # Drop the existing primary key constraint on pet_id
    op.drop_constraint('pets_pkey', 'pets', type_='primary')
    
    # Add the new UUID id column to pets table
    op.add_column('pets', sa.Column('id', sa.Uuid(), nullable=False))
    
    # Set the new id column as primary key
    op.create_primary_key('pets_pkey', 'pets', ['id'])
    
    # Update bookings.pet_id to use UUID with explicit conversion
    op.execute('ALTER TABLE bookings ALTER COLUMN pet_id TYPE UUID USING gen_random_uuid()')
    
    # Drop the old pet_id column from pets
    op.drop_column('pets', 'pet_id')
    
    # Recreate the foreign key constraint
    op.create_foreign_key(None, 'bookings', 'pets', ['pet_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Drop foreign key constraint
    op.drop_constraint(None, 'bookings', type_='foreignkey')
    
    # Add back the integer pet_id column to pets
    op.add_column('pets', sa.Column('pet_id', sa.INTEGER(), server_default=sa.text("nextval('pets_pet_id_seq'::regclass)"), autoincrement=True, nullable=False))
    
    # Drop the UUID id column
    op.drop_column('pets', 'id')
    
    # Convert bookings.pet_id back to integer (this will lose data)
    op.execute('ALTER TABLE bookings ALTER COLUMN pet_id TYPE INTEGER USING 1')
    
    # Recreate foreign key with integer reference
    op.create_foreign_key(op.f('bookings_pet_id_fkey'), 'bookings', 'pets', ['pet_id'], ['pet_id'])
    # ### end Alembic commands ###
